"""Update trusted_device model with is_active and rename columns

Revision ID: 2137bf5cf645
Revises: ffdce83a6307
Create Date: 2026-02-11 23:28:55.779424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2137bf5cf645'
down_revision = 'ffdce83a6307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_devices', sa.Column('device_token', sa.String(length=500), nullable=False))
    op.add_column('trusted_devices', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('trusted_devices', sa.Column('last_used_at', sa.DateTime(), nullable=False))
    op.alter_column('trusted_devices', 'device_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_trusted_devices_token_hash', table_name='trusted_devices')
    op.create_index(op.f('ix_trusted_devices_device_token'), 'trusted_devices', ['device_token'], unique=False)
    op.drop_column('trusted_devices', 'token_hash')
    op.drop_column('trusted_devices', 'last_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_devices', sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('trusted_devices', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_trusted_devices_device_token'), table_name='trusted_devices')
    op.create_index('ix_trusted_devices_token_hash', 'trusted_devices', ['token_hash'], unique=True)
    op.alter_column('trusted_devices', 'device_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('trusted_devices', 'last_used_at')
    op.drop_column('trusted_devices', 'is_active')
    op.drop_column('trusted_devices', 'device_token')
    # ### end Alembic commands ###
