"""Update audit_log model fields

Revision ID: 95d85ef6ae4b
Revises: 2137bf5cf645
Create Date: 2026-02-11 23:49:05.260346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95d85ef6ae4b'
down_revision = '2137bf5cf645'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('event_type', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'MFA_SETUP', 'MFA_ENABLED', 'MFA_DISABLED', 'MFA_VERIFIED', 'MFA_FAILED', 'TRUSTED_DEVICE_ADDED', 'TRUSTED_DEVICE_REVOKED', 'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_MFA_RESET', 'PASSWORD_CHANGE', 'TAX_WFH_CREATE', 'TAX_WFH_UPDATE', 'TAX_WFH_DELETE', 'TAX_WFH_EXPORT', 'TAX_TRAVEL_CREATE', 'TAX_TRAVEL_UPDATE', 'TAX_TRAVEL_DELETE', 'TAX_TRAVEL_EXPORT', 'TAX_READ_OTHER', 'FILE_UPLOAD', 'FILE_DOWNLOAD', 'FILE_DELETE', 'FINANCIAL_CREATE', 'FINANCIAL_UPDATE', 'FINANCIAL_DELETE', 'ASSET_CREATE', 'ASSET_UPDATE', 'ASSET_DELETE', 'PROJECT_CREATE', 'PROJECT_UPDATE', 'PROJECT_DELETE', 'KNOWLEDGE_CREATE', 'KNOWLEDGE_UPDATE', 'KNOWLEDGE_DELETE', name='event_type', native_enum=False), nullable=False))
    op.add_column('audit_logs', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='severity', native_enum=False), nullable=False))
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_module', table_name='audit_logs')
    op.drop_index('ix_audit_logs_success', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.drop_column('audit_logs', 'error_message')
    op.drop_column('audit_logs', 'module')
    op.drop_column('audit_logs', 'success')
    op.drop_column('audit_logs', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(length=22), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('module', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.create_index('ix_audit_logs_success', 'audit_logs', ['success'], unique=False)
    op.create_index('ix_audit_logs_module', 'audit_logs', ['module'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.drop_column('audit_logs', 'severity')
    op.drop_column('audit_logs', 'username')
    op.drop_column('audit_logs', 'event_type')
    # ### end Alembic commands ###
